export type Source = {
  id: string;
  n: number;
  title: string;
  publisher: string;
  url: string;
  kind: "Primary / official" | "Regulation" | "Industry research" | "Labour-market data" | "Provider page";
  what: string;
  checked: string;
};

/**
 * Every claim on this page that is not my own first-hand observation is tied to
 * one of these sources. Citation numbers are stable; if a URL changes I keep the
 * old entry and note the replacement rather than silently editing it.
 */
export const sources: Source[] = [
  {
    id: "dpdp-act",
    n: 1,
    title: "Digital Personal Data Protection Act, 2023 (bare Act text)",
    publisher: "Ministry of Electronics & IT, Government of India",
    url: "https://www.meity.gov.in/data-protection-framework",
    kind: "Regulation",
    what: "Consent, purpose limitation, data-principal rights and Significant Data Fiduciary duties I reference in every governance claim.",
    checked: "Aug 2026",
  },
  {
    id: "dpdp-rules",
    n: 2,
    title: "Digital Personal Data Protection Rules — notified rules and compliance timelines",
    publisher: "Ministry of Electronics & IT, Government of India",
    url: "https://www.meity.gov.in/data-protection-framework",
    kind: "Regulation",
    what: "The operational obligations Indian BAs now write into AI requirement packs (notice, consent artefacts, breach reporting).",
    checked: "Aug 2026",
  },
  {
    id: "eu-ai-act",
    n: 3,
    title: "Regulation (EU) 2024/1689 — the EU AI Act, full text",
    publisher: "EUR-Lex, European Union",
    url: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    kind: "Regulation",
    what: "Risk tiering, provider vs. deployer duties and extraterritorial reach that hits Indian IT-services and GCC delivery teams.",
    checked: "Aug 2026",
  },
  {
    id: "iso-42001",
    n: 4,
    title: "ISO/IEC 42001:2023 — AI management systems",
    publisher: "International Organization for Standardization",
    url: "https://www.iso.org/standard/81230.html",
    kind: "Primary / official",
    what: "The certification clients increasingly ask for in AI procurement checklists.",
    checked: "Aug 2026",
  },
  {
    id: "nist-rmf",
    n: 5,
    title: "AI Risk Management Framework (AI RMF 1.0)",
    publisher: "NIST, U.S. Department of Commerce",
    url: "https://www.nist.gov/itl/ai-risk-management-framework",
    kind: "Primary / official",
    what: "Govern/Map/Measure/Manage vocabulary used by most enterprise AI governance templates I see in Indian delivery.",
    checked: "Aug 2026",
  },
  {
    id: "nasscom",
    n: 6,
    title: "Strategic Review and AI/GCC talent reports",
    publisher: "NASSCOM",
    url: "https://nasscom.in/knowledge-center",
    kind: "Industry research",
    what: "India's tech-services headcount, GCC growth and AI-skilled talent demand-supply gap.",
    checked: "Aug 2026",
  },
  {
    id: "wef-jobs",
    n: 7,
    title: "Future of Jobs Report — skill-disruption and AI-adoption chapters",
    publisher: "World Economic Forum",
    url: "https://www.weforum.org/publications/the-future-of-jobs-report-2025/",
    kind: "Industry research",
    what: "Employer-reported AI adoption and the analytical-thinking / AI-literacy skill shift behind my role-change argument.",
    checked: "Aug 2026",
  },
  {
    id: "mckinsey-genai",
    n: 8,
    title: "The State of AI — global survey on GenAI adoption and value capture",
    publisher: "McKinsey & Company",
    url: "https://www.mckinsey.com/capabilities/quantumblack/our-insights/the-state-of-ai",
    kind: "Industry research",
    what: "Which GenAI use cases enterprises actually fund — the basis for my 'enterprise AI queue' list.",
    checked: "Aug 2026",
  },
  {
    id: "naukri",
    n: 9,
    title: "JobSpeak monthly hiring index — IT and AI/ML roles",
    publisher: "Naukri.com",
    url: "https://www.naukri.com/jobspeak",
    kind: "Labour-market data",
    what: "Direction of AI-role hiring demand in India, used only for direction, never for precise counts.",
    checked: "Aug 2026",
  },
  {
    id: "ambitionbox",
    n: 10,
    title: "Salary ranges for Business Analyst, AI Product Owner and related roles in India",
    publisher: "AmbitionBox",
    url: "https://www.ambitionbox.com/profile/business-analyst-salary",
    kind: "Labour-market data",
    what: "Self-reported ₹ bands I cross-check against Glassdoor and my own offer sightings before publishing a range.",
    checked: "Aug 2026",
  },
  {
    id: "glassdoor",
    n: 11,
    title: "India salary estimates — Business Analyst and AI-adjacent titles",
    publisher: "Glassdoor",
    url: "https://www.glassdoor.co.in/Salaries/business-analyst-salary-SRCH_KO0,16.htm",
    kind: "Labour-market data",
    what: "Second independent source for every salary band in the outcomes table.",
    checked: "Aug 2026",
  },
  {
    id: "logicmojo",
    n: 12,
    title: "AI Course — curriculum, batch dates, fees and EMI terms",
    publisher: "LogicMojo (publisher of this article)",
    url: "https://logicmojo.com/",
    kind: "Provider page",
    what: "Syllabus and commercial details for Rank #1. Disclosed conflict: I have written curriculum for this provider.",
    checked: "Aug 2026",
  },
  {
    id: "logicmojo-success",
    n: 13,
    title: "Success stories and learner outcomes",
    publisher: "LogicMojo",
    url: "https://logicmojo.com/success-story",
    kind: "Provider page",
    what: "Named learner outcomes readers should verify themselves on LinkedIn before trusting any placement claim.",
    checked: "Aug 2026",
  },
  {
    id: "iiba",
    n: 14,
    title: "IIBA competency guidance and AI-for-BA learning pathway",
    publisher: "International Institute of Business Analysis",
    url: "https://www.iiba.org/",
    kind: "Provider page",
    what: "Professional-body framing, endorsed-provider model and certification prerequisites.",
    checked: "Aug 2026",
  },
  {
    id: "ms-ai900",
    n: 15,
    title: "Exam AI-900: Microsoft Azure AI Fundamentals — skills outline and exam fee",
    publisher: "Microsoft Learn",
    url: "https://learn.microsoft.com/en-us/credentials/certifications/azure-ai-fundamentals/",
    kind: "Provider page",
    what: "Module list, exam pricing in ₹ and the Copilot / Power Platform analyst pathway.",
    checked: "Aug 2026",
  },
  {
    id: "dlai",
    n: 16,
    title: "AI for Everyone and the short-course catalogue",
    publisher: "DeepLearning.AI",
    url: "https://www.deeplearning.ai/courses/",
    kind: "Provider page",
    what: "Course length, free-audit availability and GenAI topic coverage.",
    checked: "Aug 2026",
  },
  {
    id: "ibm",
    n: 17,
    title: "Business Analyst and AI Foundations Professional Certificates",
    publisher: "IBM / Coursera",
    url: "https://www.coursera.org/professional-certificates/ibm-business-analyst",
    kind: "Provider page",
    what: "Certificate structure, monthly subscription pricing and project list.",
    checked: "Aug 2026",
  },
  {
    id: "simplilearn",
    n: 18,
    title: "Business Analyst and AI-augmented Masters programs",
    publisher: "Simplilearn",
    url: "https://www.simplilearn.com/",
    kind: "Provider page",
    what: "Program inclusions, ₹ fees, EMI options and stated job-assistance terms.",
    checked: "Aug 2026",
  },
  {
    id: "upgrad",
    n: 19,
    title: "Business Analytics and AI programs with university partners",
    publisher: "UpGrad",
    url: "https://www.upgrad.com/",
    kind: "Provider page",
    what: "Credential partner, duration, ₹ fees and placement-support wording.",
    checked: "Aug 2026",
  },
  {
    id: "greatlearning",
    n: 20,
    title: "PG Programs in Business Analytics and AI",
    publisher: "Great Learning",
    url: "https://www.mygreatlearning.com/",
    kind: "Provider page",
    what: "Curriculum weighting between analytics and GenAI, plus ₹ fee tiers.",
    checked: "Aug 2026",
  },
  {
    id: "intellipaat",
    n: 21,
    title: "AI and Generative AI program pages",
    publisher: "Intellipaat and Analytics Vidhya",
    url: "https://intellipaat.com/",
    kind: "Provider page",
    what: "Batch cadence, project counts and support terms for the mid-tier bracket.",
    checked: "Aug 2026",
  },
  {
    id: "budget-tier",
    n: 22,
    title: "Vernacular and low-cost GenAI catalogues",
    publisher: "GUVI, PW Skills, Udemy, LinkedIn Learning",
    url: "https://www.guvi.in/",
    kind: "Provider page",
    what: "Hindi/Tamil/Telugu delivery and the sub-₹30,000 pricing I quote for the budget tier.",
    checked: "Aug 2026",
  },
  {
    id: "ugc-online",
    n: 23,
    title: "Recognition rules for online and ODL degree programmes",
    publisher: "University Grants Commission, India",
    url: "https://www.ugc.gov.in/deb/",
    kind: "Regulation",
    what: "What a 'university-affiliated' certificate does and does not mean for Indian employers.",
    checked: "Aug 2026",
  },
  {
    id: "asci",
    n: 24,
    title: "Guidelines for advertising by education and coaching institutions",
    publisher: "Advertising Standards Council of India",
    url: "https://www.ascionline.in/",
    kind: "Regulation",
    what: "Why '100% placement' claims must be read as service promises — the basis of my red-flag checklist.",
    checked: "Aug 2026",
  },
];

export const sourceById: Record<string, Source> = Object.fromEntries(
  sources.map((s) => [s.id, s]),
);

/** Provider pages a reader should open to verify a specific course, by rank. */
export const verifyByRank: Record<number, string[]> = {
  1: ["logicmojo", "logicmojo-success"],
  2: ["iiba"],
  3: ["ms-ai900"],
  4: ["dlai"],
  5: ["ibm"],
  6: ["simplilearn"],
  7: ["upgrad", "ugc-online"],
  8: ["greatlearning", "ugc-online"],
  9: ["intellipaat"],
  10: ["budget-tier"],
};
